Testing
Svartstein/oop-school-library pull request #7
Opened 2023-03-30 20:24 UTC by chiztechnology

Hello dear reviewer. 👋 
In this PR we performed testing on Ruby following the project requirements below:

### Highlights
Add unit tests for all the methods in all the classes:

- Book
- Person
- Student
- Teacher
- Classroom
- Rental

2023-03-30 21:23 UTC, Felix45 requested changes
Hi @Swarzstein  & @chiztechnology , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966" />

## Highlights :heavy_check_mark: 
- [x] No linter errors :white_check_mark: 
- [x] All tests are passing as expected :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark:  
- [x] Descriptive pull request title and summary :white_check_mark:  

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 21:23 UTC, Felix45 commented on spec/book_spec.rb
> +describe Book do
- [ Required ] Please consider adding a unit test for the `add_rental` and `to_json` methods in your class `Book`, the project requirements state that all methods in your classes need to be tested.

## Project requirements
![Screenshot from 2023-03-30 23-55-19](https://user-images.githubusercontent.com/16392046/228962573-8389fc09-4ce6-42de-b1af-aefd25f2d036.png)

2023-03-30 21:23 UTC, Felix45 commented on spec/classroom_spec.rb
> +      array = [] # array = Array.new
Please consider removing any pieces of commented code in your repository this is because commented code makes your repository look unprofessional.

2023-03-30 21:23 UTC, Felix45 commented on spec/person_spec.rb
> +describe Person do
- [ Required ] Please consider adding a unit test for the `off_age`, `add_rental`, `correct_name`, and `to_json` methods in your class `Person`, the project requirements state that all methods in your classes need to be tested.

## Project requirements
![Screenshot from 2023-03-30 23-55-19](https://user-images.githubusercontent.com/16392046/228962573-8389fc09-4ce6-42de-b1af-aefd25f2d036.png)

2023-03-30 21:23 UTC, Felix45 commented on spec/rental_spec.rb
> +describe Rental do
- [ Required ] Please consider adding a unit test for the `to_json` method in your class `Rental`, the project requirements state that all methods in your classes need to be tested.

## Project requirements
![Screenshot from 2023-03-30 23-55-19](https://user-images.githubusercontent.com/16392046/228962573-8389fc09-4ce6-42de-b1af-aefd25f2d036.png)

2023-03-30 21:23 UTC, Felix45 commented on spec/student_spec.rb
> +describe Student do
- [ Required ] Please consider adding a unit test for the `play_hooky` and `classroom` methods in your class `Student`, the project requirements state that all the methods in your classes need to be tested.

## Project requirements
![Screenshot from 2023-03-30 23-55-19](https://user-images.githubusercontent.com/16392046/228962573-8389fc09-4ce6-42de-b1af-aefd25f2d036.png)

2023-03-30 21:23 UTC, Felix45 commented on spec/book_spec.rb
- [ Required ] Please consider adding unit test cases for all the methods in the classes that you created while implementing the Decorator design pattern. These classes include the following
  - Decorator
  - TrimmerDecorator
  - CapitalizeDecorator

## Project requirements
![Screenshot from 2023-03-30 23-55-19](https://user-images.githubusercontent.com/16392046/228966181-3dff53c7-3398-4934-ae0a-c8403e69dbe8.png)

2023-03-31 00:58 UTC, Reem-lab approved these changes
# Hi Team,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥💯💯
<img src="https://media2.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif"/>

## Highlights 🔥🔥🔥🔥
- Followed Gitflow ✅
- No Linters error 🤩🔥💯
- Great working on the tests 🔥🔥
- Descriptive PR 💯💯
- Professional README 🔥🔥



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 01:29 UTC, merged